#!/bin/bash

project_dir=`realpath run_iuv | rev | cut -d'/' -f 2- | rev`
klee_lib=${project_dir}/klee/lib
crest_lib=${project_dir}/crest/lib
export LD_LIBRARY_PATH=$klee_lib:$crest_lib:$LD_LIBRARY_PATH
export KLEE_RUNTIME_LIBRARY_PATH=$klee_lib
export PYTHONPATH=${project_dir}/lib/py
python3 ${project_dir}/iuv/iuv.py $@
