#!env python3

import os
import sys

sys.dont_write_bytecode = True

if sys.platform.startswith('cygwin'):
    print("Warning: It seems you're running TBF on cygwin - this is not officially supported.", file=sys.stderr)

elif not sys.platform.startswith('linux'):
    sys.exit("TBF currently only runs on Linux - exiting.")

script = os.path.realpath(__file__)
project_dir = os.path.dirname(script)

klee_lib = os.path.join(project_dir, "klee", "lib")
os.environ['KLEE_RUNTIME_LIBRARY_PATH'] = klee_lib

crest_lib = os.path.join(project_dir, "crest", "lib")

new_ld_path = [klee_lib, crest_lib]
if 'LD_LIBRARY_PATH' in os.environ:
    new_ld_path = new_ld_path + os.environ['LD_LIBRARY_PATH']
os.environ['LD_LIBRARY_PATH'] = ':'.join(new_ld_path)

pythonpath = os.path.join(project_dir, "lib", "py")
sys.path.insert(0, pythonpath)

import tbf
sys.exit(tbf.main())
