#!/bin/bash

project_dir=`realpath run_tbf | rev | cut -d'/' -f 2- | rev`
klee_lib=${project_dir}/klee/lib
klee_include=${project_dir}/klee/include
klee_bin=${project_dir}/klee/bin
export LD_LIBRARY_PATH=$klee_lib:$LD_LIBRARY_PATH
export KLEE_RUNTIME_LIBRARY_PATH=$klee_lib
export PATH=$klee_bin:$PATH

klee_cmd='klee'
arg_length=$(($#-1))
klee_args=${@:1:$arg_length}
input_file=${@: -1}

clang_cmd="clang -I $klee_include -emit-llvm -c -g -o out.bc $input_file"
klee_cmd="$klee_cmd `echo $klee_args` out.bc"
echo "$clang_cmd"
$clang_cmd
echo "$klee_cmd"
$klee_cmd


