#!/bin/bash

platform="`uname -s`"

case "$platform" in
    Linux|CYGWIN*)
        script="`readlink -f "$0"`"
        project_dir="$(readlink -f "$(dirname "$script")")"
        ;;
    *)
        project_dir="`dirname "$0"`"
        ;;
esac
klee_lib=${project_dir}/klee/lib
crest_lib=${project_dir}/crest/lib
export LD_LIBRARY_PATH=$klee_lib:$crest_lib:$LD_LIBRARY_PATH
export KLEE_RUNTIME_LIBRARY_PATH=$klee_lib
export PYTHONPATH=${project_dir}/lib/py
export PATH=${project_dir}/validators/cpachecker/scripts:$PATH
python3 ${project_dir}/iuv/iuv.py $@
